### ISSUE TITLE
Blit32bppImage Segfaults Intermittently

### ISSUE THREAD

**Issue by CKraniak** [FreeRCT/FreeRCT#135]
The function has segfaulted twice on me, but it's inconsistent.

When I was fixing the SDL problem, I was able to discover blit segfaults are due to dereferencing `src_base`. This could mean that `mem` is being reallocated at a different timev than the variables that control `src_base`. I don't really understand why pointer math is being used here, but it _usually_ works flawlessly.

The first time it segfaulted I was moving the FreeRCT window around my desktop, maximizing it, minimizing it, etc. I tried briefly to make it segfault again, and was unsuccessful. If I had to guess, I'd say that `mem` was resized and `src_base` was not made aware of this because of some flaw in how the frame generation works, but the nature of the flaw means the window resize has to hit at exactly the right part of the tick cycle. It's kind of a guess.

The second time it segfaulted was when I built a roller coaster to space and it got too high. Dr. MinGW tells me it was Blit32bppImage; I would have otherwise thought it was not related to blitting. I haven't looked to see how this came about.

Since the second segfault, I'm not so sure my theory about window resizing at the exact right part of the update is actually the problem.

**Comment by Noordfrees** [comment]
I wonder if this bug does still happen or if it was fixed by b0bba2d2944620ad66b4392b7d4d31ff96962ecb (#164)

**Comment by Alberth289346** [comment]
I severely doubt that region check is of much use.
You only check that `src_base` was sane at the start by testing the _same_ computed boolean value a zillion times inside the loop for reasons beyond me (one test would be enough I'd think).

I don't exactly remember what happens to `src_base`, but
a. If `src_base` doesn't move, it is 99,9% likely not at the address where data is stored.
b. If it does move, your boolean value only checks the initial position.

But 5 years is a long time, it could well have been a bug in SDL that has possibly been fixed now.
Also, if we move to OpenGL, the entire problem solves itself.

**Comment by Noordfrees** [comment]
That was fixed in 9d15963b7094b37554d8910ffc4773246dcf4126. I picked the wrong commit to mention (sorry), The link to the final result is https://github.com/FreeRCT/FreeRCT/commit/9594452970e5b63a0b5d5a3462bee57af3ff96ca#diff-9334c281e58a62dfa839929ef90ba8ffce06319c323fcd194f381586981802e6

**Comment by Alberth289346** [comment]
Ok, that works better, but it allows `src_base` near the bottom right of the area, from where you then can draw a large sprite.
That is, it doesn't look air-tight to me.

Whether it actually does anything, nobody knows I think. Your test may skip painting some pixels, but it's highly unlikely we will ever observe that. So effectively, you are hiding any bad behavior there. Works great for not crashing, but it also hides bad behavior.
This is why I generally prefer `assert`. It's annoying to have a crash I agree, but at least you know something is wrong so you can check it and try to fix it.
