### ISSUE TITLE
Remove need to manually create a font configuration file

### ISSUE THREAD

**Issue by Newbytee** [FreeRCT/FreeRCT#151]
I think one thing that may throw off less technically knowledgeable people interested in trying out FreeRCT is that the font configuration file needs to manually be created. I imagine it would be possible to let users manually create this file if desired, and use (hopefully) sensible defaults if it is not present.

**Comment by Alberth289346** [comment]
Simple solution could be to include a free TTF file in the distribution at least, and use that as default if there is no configuration file.
That also works if the user doesn't have such files available.
