### ISSUE TITLE
Link in about section of repository leads to scam website

### ISSUE THREAD

**Issue by Newbytee** [FreeRCT/FreeRCT#152]
![image](https://user-images.githubusercontent.com/4428753/105489559-b590d000-5cb3-11eb-9050-f1757beac3cf.png)
Clicking on the link shown in this screenshot presents a scam website. I therefore suggest that it is removed. Maybe it could be replaced by GitHub pages if someone is interested in settings that up, but I imagine that would require some effort.

**Comment by Alberth289346** [comment]
Fixed, took a while before I found the right button.

**Comment by Alberth289346** [comment]
We do seem to have some github pages, it contains the generated doxygen output, I think
