### ISSUE TITLE
Link on organisation page leads to scam website

### ISSUE THREAD

**Issue by Newbytee** [FreeRCT/FreeRCT#156]
Similar to https://github.com/FreeRCT/FreeRCT/issues/152, the link on the organisation's page leads to some scam website when clicked:
![image](https://user-images.githubusercontent.com/4428753/105627753-febe5c80-5e38-11eb-8c05-65b51c6e2d2d.png)

**Comment by Alberth289346** [comment]
And another link removed, thanks

**Comment by Noordfrees** [comment]
There's another one in the About sidebar at https://github.com/FreeRCT/FreeRCT-oldsvn

**Comment by Alberth289346** [comment]
Also removed
