### ISSUE TITLE
Timeout for Apple CI build

### ISSUE THREAD

**Issue by Alberth289346** [FreeRCT/FreeRCT#174]
Currently, both Linux builds take a few minutes, the first(?) Apple build isn't done after 50 minutes so something is wrong :p 

It may have to do with OS 9 being officially dead now.

@LordAro  Can you help?

Fixing is one option, but I can also totally live without Apple build.

**Comment by Noordfrees** [comment]
The travis failure is a timeout while installing and updating the dependencies. Using Homebrew on Travis's MacOS builds causes this pretty often. Perhaps this might help https://github.com/widelands/widelands/pull/4564/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R6

**Comment by Alberth289346** [comment]
Feel free to try it, it should work if you make a branch and a PR with the change.
I am horrible with automagic build things.
