### ISSUE TITLE
Crashes when roller coaster is about to arrive

### ISSUE THREAD

**Issue by fnetX** [FreeRCT/FreeRCT#228]
From time to time, when a roller coaster train is about to arrive at the station, the game crashes with

~~~
NOT_REACHED triggered at line 1497 of ~/FreeRCT/src/coaster.cpp
Aborted
~~~

Is there some work around for this?

**Comment by Noordfrees** [comment]
Hi @fnetX and thanks for the bug report. It would be helpful to know what your coaster looks like exactly, and also the layout of paths around it – can you provide a screenshot of the coaster and/or a savegame?

**Comment by fnetX** [comment]
![image](https://user-images.githubusercontent.com/19634137/149509194-d8ac564b-c501-4b88-acf8-827b08c8465b.png)
[neu001.fct.zip](https://github.com/FreeRCT/FreeRCT/files/7870056/neu001.fct.zip)
This game crashed after two rounds of the coaster on my machine. But I initially noticed this behaviour with a much simpler coaster design, too. Maybe I did something wrong, so if the crash can't immediately fixed I'd appreciate some hints for a workaround.

By the way, thank you for working on the game. I suppose it's a lot of work to bring this into a mature state, but I already like it. My little brother asked for some coaster game yesterday, and I expected to find nothing Open Source for it. OpenRCT requires to buy the proprietary license, so I was very happy to find this simple yet (mostly) working game. With a few bugfixes, this is playable.

**Comment by fnetX** [comment]
Noticable might be the track near the stop point of the train, as well as the fact that I might (not sure, but well possible) placed the last track with planks to the side at the very end of the whole track (so I might initially have only placed two of them).

But I tried replacing one of the end tracks with a normal track, and this didn't work for me either, IIRC.

**Comment by Noordfrees** [comment]
Thanks, I can reproduce the issue. This is most likely the cause:

> the fact that I might (not sure, but well possible) placed the last track with planks to the side at the very end of the whole track (so I might initially have only placed two of them).

I did not consider this possibility when I wrote the station tracking code, so the station appears to be treated like two different stations in some ways. I will investigate and prepare a fix this evening.
