### ISSUE TITLE
[Discussion] New Website

### ISSUE THREAD

**Issue by Noordfrees** [FreeRCT/FreeRCT#232]
I'd just like to mention that the new website https://freerct.net/ I've been working on the last two weeks is now pretty much ready. The repository is located at https://github.com/Noordfrees/FreeRCT-website.

- Do we want to declare the website official now, and move ownership of the repo to @FreeRCT?

- The old static website can then be taken offline again, and also removed from the repo.

- Discussion regarding style, bugs, suggestions, … should best take place in the new [users' & developers' forum](https://freerct.net/forum/8).

- The website is not actually *finished* yet, there's still a lot of stuff missing that I want to implement: private messages (the links on the user profile pages don't work yet); a wiki; better navigation; automated deployment of development builds after #207, …
  None of this is really critical though IMHO, and no features of the old static website are missing on the new one.

- @Alberth289346 @LordAro Do you want to be website administrators and/or get access to the server? If so please create an account on the website and confirm your username here, and we'll discuss details via e-mail.

**Comment by Alberth289346** [comment]
Great progress.
I just made you owner of the FreeRCT organization as well. I want neither web-admin nor server access at this time. In fact I am somewhat pondering to move further away from the project, although I am not in a hurry to do so.
