### ISSUE TITLE
Flathub publishing

### ISSUE THREAD

**Issue by Newbytee** [FreeRCT/FreeRCT#235]
Now that https://github.com/FreeRCT/FreeRCT/pull/225 is merged, it's possible to create Flatpak builds of FreeRCT. However, they are not distributed anywhere! I think a good place to publish FreeRCT would be [Flathub](https://flathub.org). My idea is that we'd publish the FreeRCT on Flathub together with the initial 0.1 release (or whatever number it ends up having) so that people across various Linux distributions can try it out and don't have to build it themselves or wait for distributions to package it. All that's missing right now is really making that tag and then making a pull request to Flathub that adds it (and ideally also fixing https://github.com/FreeRCT/FreeRCT/issues/231).

However, there is the question of who should maintain and submit it. Flathub prefers the upstream developers to maintain the Flathub Flatpak, but it can be done with someone else (e.g. me). That said, it could be both of us as Flathub allows you to have multiple maintainers per repo.

**Comment by Noordfrees** [comment]
I'd appreciate it if you could do this since you already have experience with Flatpak/Flathub. 
If @Alberth289346 is OK with this we could make you a member of the @FreeRCT organization. Then you could publish and maintain the Flatpak package officially and if you want to stop sometime someone else could take over seamlessly.

**Comment by Newbytee** [comment]
Sounds good to me if he's okay with that.

**Comment by Alberth289346** [comment]
I am fine with it. However as I have no understanding of flathubs, I cannot do reviews etc, so I'll leave that to @Noordfrees .

**Comment by Newbytee** [comment]
At this point all that's missing is a tag as Flathub only accepts software with releases from what I understand. Once we've made a tag/branch I'll submit FreeRCT to Flathub and respond to reviews. I can tell them to wait with merging it until the 19th of March if we want to wait until then though. Do any of you want to be added as co-maintainers of the Flathub repo that will be created? It's a repo that just stores the Flatpak manifest and patches (if necessary) more or less. An example: https://github.com/flathub/org.widelands.Widelands

**Comment by Newbytee** [comment]
I've created a draft pull request at Flathub now: https://github.com/flathub/flathub/pull/2917. I'll mark it as ready once v0.1 has been tagged.

**Comment by Newbytee** [comment]
Weird, the Flathub builder is unable to download the screenshots. Is there anything in the logs or such that could hint towards what's going on? https://flathub.org/builds/#/builders/10/builds/9750/steps/10/logs/stdio

**Comment by Noordfrees** [comment]
Attempting to access freerct.net with command-line `curl` also fails with a "curl: (60) SSL certificate problem: unable to get local issuer certificate" error. Probably I made some error with the server's SSL configuration (it's the first time I set up a webserver). I'll have a look at it later today and will report back when I figured it out.

**Comment by Noordfrees** [comment]
Can you please retry if my config change fixed it?

**Comment by Newbytee** [comment]
> Can you please retry if my config change fixed it?

Seems to work now! It's just complaining that the release I set is in the future, but that shouldn't be a problem when we actually do the release.

**Comment by Newbytee** [comment]
I forgot about this issue. Should be done now.
