### ISSUE TITLE
Missing DLLs under Wine

### ISSUE THREAD

**Issue by Noordfrees** [FreeRCT/FreeRCT#254]
I've tried to run the FreeRCT 0.1 Windows x64 executable in Wine, and although the installer completes fine, the program fails to start:
```
$ wine Program\ Files/FreeRCT/bin/freerct.exe 
0030:err:module:import_dll Library SDL2.dll (which is needed by L"C:\\Program Files\\FreeRCT\\bin\\freerct.exe") not found
0030:err:module:import_dll Library SDL2_ttf.dll (which is needed by L"C:\\Program Files\\FreeRCT\\bin\\freerct.exe") not found
0030:err:module:import_dll Library MSVCP140D.dll (which is needed by L"C:\\Program Files\\FreeRCT\\bin\\freerct.exe") not found
0030:err:module:import_dll Library VCRUNTIME140D.dll (which is needed by L"C:\\Program Files\\FreeRCT\\bin\\freerct.exe") not found
0030:err:module:import_dll Library VCRUNTIME140_1D.dll (which is needed by L"C:\\Program Files\\FreeRCT\\bin\\freerct.exe") not found
0030:err:module:import_dll Library ucrtbased.dll (which is needed by L"C:\\Program Files\\FreeRCT\\bin\\freerct.exe") not found
0030:err:module:LdrInitializeThunk Importing dlls for L"C:\\Program Files\\FreeRCT\\bin\\freerct.exe" failed, status c0000135
```

Versions:
- FreeRCT 0.1
- Wine wine-5.0.3 (Ubuntu 5.0.3-3ubuntu2)
- Ubuntu MATE 21.10

I don't know if this problem will also occur on real Windows installations or is specific to Wine. Marking this bug as enhancement because it's about supporting a currently untested setup.

Possible solutions: Either bundle the listed DLLs with the binary, or create a statically linked executable. The latter would be cleaner but probably also harder. Help from someone who is familiar with Windows packaging appreciated…

**Comment by Alberth289346** [comment]
SDL2 libraries should be provided by us in the package probably (or compiled into the binary as you say). At least the VCRUNTIME things are runtime support for the VC generated code. That should be available from the Windows compiler that you used. The other libraries I have no idea at all.

**Comment by Noordfrees** [comment]
Tried again with a current development branch, and interestingly I only see this bug with Release binaries. Debug binaries on the other hand work fine in Wine.

---

Edit: Don't know how this happened but now the problem occurs with both configurations.
The compiler output logs show a lot of `cl : Command line warning D9025 : overriding '/MT' with '/MDd'` which is clearly relevant here (`/MD`, the default, is for dynamic linking, `/MT` for static linking; with `d` at the end builds a debug build, without it it builds a release build).
