### ISSUE TITLE
Building for MacOS

### ISSUE THREAD

**Issue by Flipp3rrr** [FreeRCT/FreeRCT#260]
I noticed MacOS is not officially supported, so I tried compiling it and it turns out all dependencies can be installed with Homebrew (`$ brew install flex bison libpng sdl2 sdl2_ttf cmake make`) after which a functional executable can be produced (`cmake && make && make install`).

I've made a fork ([Flipp3rrr/FreeRCT](https://github.com/Flipp3rrr/FreeRCT)) at first, but since it's quite trivial i'm unsure if I should submit a pull request.

System specifications:
- MacOS Big Sur 11.6.1
- 1,1 GHz Quad-Core Intel Core i5
- 8 GB 3733 MHz LPDDR4X
- Intel Iris Plus Graphics 1536 MB

I've also added a screenshot of FreeRCT running under MacOS Big Sur below:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/33151653/159685516-c7df1991-4883-468f-acc6-89fb9547ae6b.png">

**Comment by Flipp3rrr** [comment]
Saving & loading appears to be broken, but this might be a bug in FreeRCT itself.

Loading a previously saved game caused the following crash:

```sh
$ freerct
ERROR: Loading '/Users/flipp3rrr/.local/share/freerct/save/Park Test.fct' failed: Missing pattern name for cstc
Assertion failed: (anim_type >= ANIM_BEGIN && anim_type <= ANIM_LAST), function GetAnimationSprite, file /Users/flipp3rrr/Documents/GitHub/FreeRCT/src/sprite_store.h, line 656.
[1]    48035 abort      freerct
```

This is what the park in my original message looked like after loading it as a saved game:

<img width="912" alt="image" src="https://user-images.githubusercontent.com/33151653/159688724-db886c46-7c3a-4d57-ab2c-5f3c824cb60c.png">

Closing the game with the red `x` on the top left also caused the following crash:

```sh
$ freerct
ERROR: Loading '/Users/flipp3rrr/.local/share/freerct/save/Park Test.fct' failed: Missing pattern name for cstc
Assertion failed: (voxel), function RemoveFromWorld, file /Users/flipp3rrr/Documents/GitHub/FreeRCT/src/track_piece.cpp, line 178.
[1]    49386 abort      freerct
```

Here's the savegame file:

[Park Test.fct.zip](https://github.com/FreeRCT/FreeRCT/files/8332562/Park.Test.fct.zip)

**Comment by Newbytee** [comment]
> I've made a fork ([Flipp3rrr/FreeRCT](https://github.com/Flipp3rrr/FreeRCT)) at first, but since it's quite trivial i'm unsure if I should submit a pull request.

Maybe you could the instructions under troubleshooting like it's been done for Debian/Ubuntu?

**Comment by Flipp3rrr** [comment]
> Maybe you could the instructions under troubleshooting like it's been done for Debian/Ubuntu?

I agree, I didn't notice that section until your comment and now moved the instructions for the dependencies to the troubleshooting section. Having done that, I'm still not sure if I should open a pull-request.

**Comment by Newbytee** [comment]
I think you should.

**Comment by Noordfrees** [comment]
Do you happen to know how to package the build artifacts as a DMG that can then be uploaded by the CI? I tried it in #207 but couldn't get it to work so it was removed. It would be good if we could distribute ready-to-install packages for MacOS like we do for Windows and Ubuntu.

**Comment by Flipp3rrr** [comment]
> Do you happen to know how to package the build artifacts as a DMG that can then be uploaded by the CI? I tried it in #207 but couldn't get it to work so it was removed. It would be good if we could distribute ready-to-install packages for MacOS like we do for Windows and Ubuntu.

I can see if I can get that to work! :)

**Comment by Flipp3rrr** [comment]
I've been making some progress over at [Flipp3rrr/FreeRCT](https://github.com/Flipp3rrr/FreeRCT) to get a functional `.app` bundle and `.dmg`. I'm just having some trouble with the executable :(

**Comment by Flipp3rrr** [comment]
I'm closing this, since there's not much more to say that can't be said in the PR.
