### ISSUE TITLE
Cannot run prebuilt windows binary(x64)

### ISSUE THREAD

**Issue by YJSoft** [FreeRCT/FreeRCT#269]
Env : Windows 11(22000.675)

I tried

1. 0.1 Installer from `freerct.net`
2. Installer exe from github
3. Portable zip from github

None of above works. just nothing. No error message, or window.

**Comment by Noordfrees** [comment]
Can you try whether manually setting the install dir fixes it? To do so open a command line prompt and run:
```
"C:\Path\To\freerct.exe" --installdir "C:\Path\To\Installation\Directory"
```
The installation directory is the one that should have two folders called `data` and `rcd` in it (e.g. if you extracted the latest ZIP it would be `...\freerct-0.2~git1-c09dc7f-windows-win64\share\freerct`).

**Comment by RetroSoftwareRepository** [comment]
The installer also doesn't come with the required 64-bit DLLs.

**Comment by LoveBodhi** [comment]
I download latest daily build (Portable Zip), still NO required DLL's, even 32-bit!!
