### ISSUE TITLE
32bpp Image Data Layout Is Messed Up

### ISSUE THREAD

**Issue by Noordfrees** [FreeRCT/FreeRCT#291]
<details>
<summary>TL;DR</summary>
To reproduce, add the following code at the end of `ImageData::Load32bpp`, then compile with ASan enabled and try to start.

```c++
	for (int x = 0; x < this->width; ++x) {
		for (int y = 0; y < this->height; ++y) {
			uint32 colour = this->GetPixel(x, y);
		}
	}
```

I guarantee that one of the first images loaded will cause a crash with a heap-buffer-overflow. It seems to happen at random locations, anywhere inside the image. Adding log data before every `GetPixel` call in the snippet above, the first output after starting is:
```
[100%] Built target freerct
NOCOM 32bpp [ 47x 29]   0x  0
NOCOM 32bpp [ 47x 29]   0x  1
NOCOM 32bpp [ 47x 29]   0x  2
=================================================================
==117653==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x617000000b1f at pc 0x5607b284738a bp 0x7ffdc4c8b6c0 sp 0x7ffdc4c8b6b8
READ of size 1 at 0x617000000b1f thread T0
    #0 0x5607b2847389 in ImageData::GetPixel(unsigned short, unsigned short, Recolouring const*, GradientShift) const /home/benedikt/frct/freerct/src/sprite_data.cpp:201:20
    #1 0x5607b2848182 in ImageData::PostLoad() /home/benedikt/frct/freerct/src/sprite_data.cpp:253:26
    #2 0x5607b2848549 in LoadImage(RcdFileReader*) /home/benedikt/frct/freerct/src/sprite_data.cpp:284:8
    #3 0x5607b28594d3 in SpriteManager::Load(char const*) /home/benedikt/frct/freerct/src/sprite_store.cpp:1363:21
    #4 0x5607b285bdfc in SpriteManager::LoadRcdFiles() /home/benedikt/frct/freerct/src/sprite_store.cpp:1582:10
    #5 0x5607b26e411b in freerct_main(int, char**) /home/benedikt/frct/freerct/src/freerct.cpp:212:18
    #6 0x5607b290f9e1 in main /home/benedikt/frct/freerct/src/unix/main_unix.cpp:22:7
    #7 0x7ff6b8483d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #8 0x7ff6b8483e3f in __libc_start_main csu/../csu/libc-start.c:392:3
    #9 0x5607b25828f4 in _start (/home/benedikt/frct/freerct/build/bin/freerct+0x1568f4) (BuildId: 19917b9e83e8f595ebdebd02563d739fe31a45b4)

0x617000000b1f is located 261 bytes to the right of 666-byte region [0x617000000780,0x617000000a1a)
allocated by thread T0 here:
    #0 0x5607b264061d in operator new[](unsigned long) (/home/benedikt/frct/freerct/build/bin/freerct+0x21461d) (BuildId: 19917b9e83e8f595ebdebd02563d739fe31a45b4)
    #1 0x5607b2845e31 in ImageData::Load8bpp(RcdFileReader*, unsigned long) /home/benedikt/frct/freerct/src/sprite_data.cpp:52:19
    #2 0x5607b2848487 in LoadImage(RcdFileReader*) /home/benedikt/frct/freerct/src/sprite_data.cpp:280:9
    #3 0x5607b28594d3 in SpriteManager::Load(char const*) /home/benedikt/frct/freerct/src/sprite_store.cpp:1363:21
    #4 0x5607b285bdfc in SpriteManager::LoadRcdFiles() /home/benedikt/frct/freerct/src/sprite_store.cpp:1582:10
    #5 0x5607b26e411b in freerct_main(int, char**) /home/benedikt/frct/freerct/src/freerct.cpp:212:18
    #6 0x5607b290f9e1 in main /home/benedikt/frct/freerct/src/unix/main_unix.cpp:22:7
    #7 0x7ff6b8483d8f in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/benedikt/frct/freerct/src/sprite_data.cpp:201:20 in ImageData::GetPixel(unsigned short, unsigned short, Recolouring const*, GradientShift) const
Shadow bytes around the buggy address:
  0x0c2e7fff8110: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8120: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8130: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c2e7fff8140: 00 00 00 02 fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff8150: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
=>0x0c2e7fff8160: fa fa fa[fa]fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff8170: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff8180: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff8190: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff81a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c2e7fff81b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==117653==ABORTING
```
Depending on which image is loaded first, the invalid access may occur in a different line in `GetPixel`. The memory access is always a small number of bytes after the end of the allocated data, sometimes just off by very few bytes, sometimes several lines of ASan shadow bytes.

The crashes only happen in 32bpp images; 8bpp images seem to be fine.

For reference, here's the `GetPixel` implementation:
https://github.com/FreeRCT/FreeRCT/blob/d3af2c4d05c0dc1bcb428e13d223a64352fe5e5c/src/sprite_data.cpp#L160-L243
And the file format documentation:
https://github.com/FreeRCT/FreeRCT/blob/d3af2c4d05c0dc1bcb428e13d223a64352fe5e5c/developer_documentation/data_format.rst#L186-L244

Or maybe the code emitted by RCDgen is at fault?
https://github.com/FreeRCT/FreeRCT/d3af2c4d05c0dc1bcb428e13d223a64352fe5e5c/master/src/rcdgen/image.cpp
</details>

---

**So my question is**,
does anyone understand the format of our 32bpp `ImageData` structure, what is done wrong in `ImageData::GetPixel` for 32bpp sprites, and/or how to fix the out-of-bounds memory access?

**Background** is that I am now seriously tackling the move to OpenGL/OpenGLES, and its rendering mechanism means that, for every sprite loaded from an RCD file in our own image encoding implementation, I need to create a pixel array `uint8[w * h * 4]` once after loading and fill it in with the RGBA values of every pixel in the image, which will afterwards allow rendering the image far more efficiently than the *(about-to-be-removed, hello #223 and #135)* `Blit8|32bppImages` functions ever could. This issue is the last bigger obstacle in the way to completing my graphics rewrite, everything after that will be comparatively easy.

---

Probably related: #135

**Comment by Alberth289346** [comment]
I should be able to understand it since I invented the format. It has been many years though since I last looked at it. I can also spend some time on it currently.

Do you have ideas how to go about finding the problem?
I am thinking about fuzzy testing, but not sure how to do that so it may be too complicated.

**Comment by Noordfrees** [comment]
As far as I can see there are three possibilities. One, that GetPixel interprets the data incorrectly – maybe some bitwise shift or offset constant that differs from the data format specification. Second, that RCDgen emit output that does not follow the spec – again likely some incorrect offset or bitmask. Third, that the specification itself contains a mistake that causes some impossible situation.

---

I tried to compare the GetPixel code to the spec and found two possible errors:
```diff
diff --git a/src/sprite_data.cpp b/src/sprite_data.cpp
index 6a6e58b4..83d0e1ab 100644
--- a/src/sprite_data.cpp
+++ b/src/sprite_data.cpp
@@ -206,12 +206,12 @@ uint32 ImageData::GetPixel(uint16 xoffset, uint16 yoffset, const Recolouring *re
                while (xoffset > 0) {
                        uint8 mode = *ptr++;
                        if (mode == 0) break;
-                       if ((mode & 0x3F) < xoffset) {
+                       if ((mode & 0x3F) <= xoffset) {
                                xoffset -= mode & 0x3F;
                                switch (mode >> 6) {
                                        case 0: ptr += 3 * (mode & 0x3F); break;
                                        case 1: ptr += 1 + 3 * (mode & 0x3F); break;
-                                       case 2: ptr++; break;
+                                       case 2: break;
                                        case 3: ptr += 1 + 1 + (mode & 0x3F); break;
                                }
                        } else {
```
With this patch all images *seem* to load all pixel values correctly. Could you compare this to the spec to see whether I'm on the right track here or just reading random memory?

**Comment by Alberth289346** [comment]
I agree with your changes.

**Comment by Alberth289346** [comment]
This function is however for pixel testing rather than rendering. Rendering is at `Blit32bppImages` in `video.cpp` line 729 and/or `Blit8bppImages` just above it.
