### ISSUE TITLE
Paths can be built through fences

### ISSUE THREAD

**Issue by GoogleCodeExporter** [FreeRCT/FreeRCT#56]
```
It is possible to build a path through a fence or placing a fence on top of a 
path.

I have a work-in-progress patch for this, but it is not fully working yet.
```

Original issue reported on code.google.com by `leif.li...@gmail.com` on 17 Aug 2014 at 8:32

**Comment by ghost** [comment]
@Leffe108: If it is all right, I've done some initial [work](https://github.com/FreeRCT/FreeRCT/compare/master...nicolasreed:path-fence-fixes) to fix this bug.

Feel free to let me know if this is an issue. :)
